-- Some variables to make calculations much easier
local UnitName
local BaseDamage = 0
local BaseDamage2 = 0
local BaseDamage3 = 0
local DamageType
local DamageType2
local DamageType3

local CacoLichStill = {"set-var Op1.Value = 0",
	"frame 0", "wait 4", "random-goto 99 no-rotate", "random-rotate 1", "label no-rotate", "wait 1",}
local CacoLichMove = {"unbreakable begin", 
	"if-var v_UnitFlags.Value & "..unitFlags.UF_UpgradeSpeed.." speedup",
	"if-var v_HitPoints.Percent <= 40 damaged40", 
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
    "frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 1", "goto end",
	"label damaged40",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 2",
    "frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 2", "goto end",
	"label speedup",
	"if-var v_HitPoints.Percent <= 40 speedup40", 
	"frame 0", "move 3", "wait 2", 
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 1",
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 2", "goto end",
	"label speedup40",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
    "frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 1",
	"label end", "unbreakable end", "wait 1"}
local CacoLichDeath = {"unbreakable begin", 
	"exact-frame 35", "spawn-missile missile-green-gibs 0 20 0 0 pixel", "wait 2", 
	"exact-frame 36", "wait 3", 
	"exact-frame 37", "wait 3", 
	"exact-frame 38", "wait 3", 
	"exact-frame 39", "wait 3", 
	"exact-frame 40", "wait 3", 
	"exact-frame 41", "wait 3", 
	"exact-frame 42", "spawn-unit unit-cacolich-body 0 0 2 15 summoned", 
	"set-var ArtifactGive.Max 0 v_ArtifactGive.Value l",
		"set-var ArtifactGive.Value 0 v_ArtifactGive.Value l",
		"set-var ArtifactGive.Enable 0 1 l",
		"set-var RessurectPlayer.Value 0 l_this l", 
    "unbreakable end","wait 1",}
	
DefineAnimations("animations-cacolich-body", {
  Still = {"label begin","exact-frame 42","if-var v_Arg1.Value > 0 still", "exact-frame 42","wait 1", "goto end", 
  "label ressurect", 
  "set-var UnitFlags.Value &= "..unitFlags.UF_Raising,
  "sound vgavnonah", 
  "exact-frame 42","wait 3",
  "exact-frame 41", "wait 3",
  "exact-frame 40", "wait 3",
  "exact-frame 39", "wait 3",
  "exact-frame 38", "wait 3",
  "exact-frame 37", "wait 3",
  "exact-frame 36", "wait 3", 
  "exact-frame 35", "wait 3", 
  "spawn-unit unit-cacolich 0 0 2 v_RessurectPlayer.Value jointoai.summoned", "goto end",
  "label diedemon", "die demon_eating","wait 2",	
  "label still","exact-frame 42", "wait 1", 
  "if-var v_UnitFlags.Value & "..unitFlags.UF_KillFromDemon.." diedemon",
  "if-var v_Ressurect.Value >= v_NeedToResurrect.Value ressurect", 
  "set-var Arg1.Value 2 1","goto begin","label end","die ressurect","wait 2"},
  Death = {"unbreakable begin","exact-frame 42","wait 2","unbreakable end","wait 1",},
  Death_ressurect = {"unbreakable begin","exact-frame 42","unbreakable end","wait 1",},
  Death_demon_eating = {"unbreakable begin","exact-frame 42","spawn-missile missile-gibs 20 20 0 0 pixel","wait 3","unbreakable end","wait 1",}
})

DefineAnimations("animations-cacolich", {
  Still = CacoLichStill,
  Move = CacoLichMove,
  Attack = {"unbreakable begin", 
  "set-var Op1.Value = 0",
  "set-var LightArmorDamage.Value 0 v_LightArmorDamage2.Value",
  "set-var CombatArmorDamage.Value 0 v_CombatArmorDamage2.Value",
  "set-var HeavyArmorDamage.Value 0 v_HeavyArmorDamage2.Value",
  "set-var FleshArmorDamage.Value 0 v_FleshArmorDamage2.Value",
  "set-var HeavyFleshArmorDamage.Value 0 v_HeavyFleshArmorDamage2.Value",
  "set-var AirFleshArmorDamage.Value 0 v_AirFleshArmorDamage2.Value",
  "set-var MechanicalArmorDamage.Value 0 v_MechanicalArmorDamage2.Value",
  "set-var AirMechanicalArmorDamage.Value 0 v_AirMechanicalArmorDamage2.Value",
  "set-var BuildingArmorDamage.Value 0 v_BuildingArmorDamage2.Value",
  "set-var HeavyBuildingArmorDamage.Value 0 v_HeavyBuildingArmorDamage2.Value",
  "set-var CursedArmorDamage.Value 0 v_CursedArmorDamage2.Value",
  "frame 0", "wait 3", 
  "frame 5", "wait 3",
  "frame 10", "wait 3", 
  "frame 15", "attack", "sound fireball launch", "wait 8",
  "frame 0", "wait 17", 
    "unbreakable end", "wait 1"},
  SpellCast = {"unbreakable begin",
  "if-var v_Op1.Value == 1 fire",
  "set-var LightArmorDamage.Value 0 v_LightArmorDamage3.Value",
  "set-var CombatArmorDamage.Value 0 v_CombatArmorDamage3.Value",
  "set-var HeavyArmorDamage.Value 0 v_HeavyArmorDamage3.Value",
  "set-var FleshArmorDamage.Value 0 v_FleshArmorDamage3.Value",
  "set-var HeavyFleshArmorDamage.Value 0 v_HeavyFleshArmorDamage3.Value",
  "set-var AirFleshArmorDamage.Value 0 v_AirFleshArmorDamage3.Value",
  "set-var MechanicalArmorDamage.Value 0 v_MechanicalArmorDamage3.Value",
  "set-var AirMechanicalArmorDamage.Value 0 v_AirMechanicalArmorDamage3.Value",
  "set-var BuildingArmorDamage.Value 0 v_BuildingArmorDamage3.Value",
  "set-var HeavyBuildingArmorDamage.Value 0 v_HeavyBuildingArmorDamage3.Value",
  "set-var CursedArmorDamage.Value 0 v_CursedArmorDamage3.Value",
  "frame 20", "wait 3", 
  "frame 25", "wait 3",
  "label fire",
  "set-var Op1.Value = 1",
  "frame 30",  "spawn-missile missile-cacolich-flame 0 0 0 0 damage.totarget 2",
  "attack", "sound lich flame", "wait 2",
    "unbreakable end", "wait 1"},
  Death = CacoLichDeath
})

UnitName = "unit-cacolich"
BaseDamage = UnitInfo(UnitName, const.Unit_BaseDmg)
DamageType = UnitInfo(UnitName, const.Unit_DamageType)
BaseDamage2 = UnitInfo(UnitName, const.Unit_BaseDmg2)
DamageType2 = UnitInfo(UnitName, const.Unit_DamageType2)
DefineUnitType(UnitName, { Name = _("Cacolich"),
  -- Drawing
  Image = {"file", "graphics/hell/units/cacolich.png", "size", {72, 72}},
  Shadow = {"file", "graphics/hell/units/cacolich-s.png", "size",{72, 72},"offset", {24, 24}},
  Animations = "animations-cacolich", Icon = "icon-cacolich",
  DrawLevel = UnitInfo(UnitName, const.Unit_Draw),
  TileSize = {1, 1}, BoxSize = {49, 49}, Offset = {0, -10},
  Impact = {"shell", "missile-green-shell-meat", "melee", "missile-green-melee-meat"},
  MissileOffsets = {{{0, -16}, {14, -14}, {21, -4}, {5,-3}, {0, 0}, {-11, -1}, {-21, -4}, {-16, -5}},
					{{0, 0}, {7, 8}, {11, 8}, {4, 7}, {0, 8}, {-6, 7}, {-10, 8}, {-5, 6}}},
  Flip = false, NumDirections = 8,
  Type = "fly",
  -- Properties
  Costs = {"time", UnitInfo(UnitName, const.Unit_Build), "minerals", UnitInfo(UnitName, const.Unit_MinCost), "energy", UnitInfo(UnitName, const.Unit_EngCost)},
  HitPoints = UnitInfo(UnitName, const.Unit_HP),
  PoisonDrain = 1,
  SightRange = UnitInfo(UnitName, const.Unit_Sight), ComputerReactionRange = UnitInfo(UnitName, const.Unit_Comp),
  PersonReactionRange = UnitInfo(UnitName, const.Unit_Person),
  MaxAttackRange = UnitInfo(UnitName, const.Unit_AtkRange),
  Priority = 30,
  Demand = UnitInfo(UnitName, const.Unit_Supply),
  Points = UnitInfo(UnitName, const.Unit_Points),
  Mana = UnitInfo(UnitName, const.Unit_Mana),
  ArtifactGive = UnitInfo(UnitName, const.Unit_Artifact),
  CanCastSpell = {"spell-lichflame"},
  -- Damage and armor part
  BasicDamage = 1, PiercingDamage = 1, Missile = "missile-cacolich-fire",
  IsAirFleshArmor = 1,
  BaseDamage = BaseDamage,

  LightArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 1),
  CombatArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 2),
  HeavyArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 3),
  
  FleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 4),
  HeavyFleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 5),
  AirFleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 6),
  
  MechanicalArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 7),
  AirMechanicalArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 8),
  
  BuildingArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 9),
  HeavyBuildingArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 10),
  
  CursedArmorDamage2 = GetCursedDamage(BaseDamage),
  
  LightArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 1),
  CombatArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 2),
  HeavyArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 3),
  
  FleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 4),
  HeavyFleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 5),
  AirFleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 6),
  
  MechanicalArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 7),
  AirMechanicalArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 8),
  
  BuildingArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 9),
  HeavyBuildingArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 10),
  
  CursedArmorDamage3 = GetCursedDamage(BaseDamage2),
  ----------------------
  -- Flags
  Hell = true,
  CanAttack = true,
  CanTargetLand = true,
  CanTargetSea = true,
  AirUnit = true,
  ShowArmor = true,
  organic = true,
  SelectableByRectangle = true,
  -- Other
  PriorityTarget = {"organic", "false", "AirUnit", "only", "Mechanical", "only", "Building", "only"},
  OnEachSecond = UpdateVeteranStatus,
  RightMouseAction = "attack",
  Sounds = {
    "selected", "cacolich sight",
    "acknowledge", "cacolich active",
    "ready", "cacolich sight",
    "help", "hell unit under attack",
    "dead", "cacolich death"} } )
	
DefineUnitType("unit-cacolich-body", { Name = _("Cacolich Body"),
  Image = {"file", "graphics/hell/units/cacolich.png", "size", {72, 72}},
  Animations = "animations-cacolich-body", Icon = "icon-cacolich",
  HitPoints = 150,
  DrawLevel = 10,
  IsHeavyFleshArmor = 1,
  Indestructible = 1,
  NeedToResurrect = 4,
  NumDirections = 8, Flip = false,
  NoRandomPlacing = true,
  IsResurrectable = true,
  TileSize = {1, 1}, BoxSize = {31, 31},
  SightRange = 0,
  Arg1 = 3600,
  BasicDamage = 0, PiercingDamage = 0, Missile = "missile-none",
  Priority = 0,
  Type = "land",
  NonSolid = true,
  Hell = true,
  Dead = true,
  IsNotSelectable = true,
  Sounds = {} } )