-- Some variables to make calculations much easier
local UnitName
local BaseDamage = 0
local BaseDamage2 = 0
local BaseDamage3 = 0
local DamageType
local DamageType2
local DamageType3

local BelialStill = {"frame 5", "wait 4", "random-goto 99 no-rotate","frame 10", "wait 4","frame 15", "wait 4", 
"frame 0", "wait 4","random-rotate 1", "label no-rotate", "wait 1",}
local BelialMove = {"unbreakable begin",
	"if-var v_HitPoints.Percent <= 40 damaged40", 
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 5", "move 2", "spawn-missile missile-belial-spot 0 0 0 0 pixel 2", "spawn-missile missile-belial-smoke 0 0 0 0 pixel 2", "wait 1",
	"frame 5", "move 2", "wait 2",
    "frame 10", "move 2", "wait 1", 
	"frame 10", "move 2", "wait 1",
	"frame 15", "move 2", "spawn-missile missile-belial-spot 0 0 0 0 pixel 3","spawn-missile missile-belial-smoke 0 0 0 0 pixel 3", "wait 1", 
	"frame 15", "move 2", "wait 2", 
    "frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",  
	"frame 5", "move 2", "spawn-missile missile-belial-spot 0 0 0 0 pixel 2","spawn-missile missile-belial-smoke 0 0 0 0 pixel 2", "wait 1",
	"frame 5", "move 2", "wait 2",
    "frame 10", "move 2", "wait 1", 
	"frame 10", "move 2", "wait 1",
	"frame 15", "move 2", "spawn-missile missile-belial-spot 0 0 0 0 pixel 3","spawn-missile missile-belial-smoke 0 0 0 0 pixel 3", "wait 1", 
	"frame 15", "move 2", "wait 2", "goto end",
	"label damaged40",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 5", "move 2", "spawn-missile missile-belial-spot 0 0 0 0 pixel 2","spawn-missile missile-belial-smoke 0 0 0 0 pixel 2", "wait 2", 
	"frame 5", "move 2", "wait 2",
    "frame 10", "move 2", "wait 1", 
	"frame 10", "move 2", "wait 2",
	"frame 15", "move 2", "spawn-missile missile-belial-spot 0 0 0 0 pixel 3","spawn-missile missile-belial-smoke 0 0 0 0 pixel 3", "wait 2", 
	"frame 15", "move 2", "wait 2",
    "frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",  
	"frame 5", "move 2", "spawn-missile missile-belial-spot 0 0 0 0 pixel 2","spawn-missile missile-belial-smoke 0 0 0 0 pixel 2", "wait 2", 
	"frame 5", "move 2", "wait 2",
    "frame 10", "move 2", "wait 1", 
	"frame 10", "move 2", "wait 2",
	"frame 15", "move 2", "spawn-missile missile-belial-spot 0 0 0 0 pixel 3","spawn-missile missile-belial-smoke 0 0 0 0 pixel 3", "wait 2", 
	"frame 15", "move 2", "wait 2",
	"label end", "unbreakable end", "wait 1",}
local BelialDeath = {"unbreakable begin", 
	"exact-frame 80", "spawn-missile missile-brown-gibs 20 20 0 0 pixel", "wait 4",
	"exact-frame 81", "wait 4", 
	"exact-frame 82", "wait 4",
	"exact-frame 83", "wait 4", 
	"exact-frame 84", "wait 4", 
	"exact-frame 85", "wait 4", 
	"exact-frame 86", "wait 4", 
	"exact-frame 87", "wait 4",
	"exact-frame 88", "wait 4",
	"exact-frame 89", "spawn-unit unit-belial-body 0 0 2 15",
	"set-var ArtifactGive.Max 0 v_ArtifactGive.Value l",
		"set-var ArtifactGive.Value 0 v_ArtifactGive.Value l",
		"set-var ArtifactGive.Enable 0 1 l",
	"exact-frame 89", "unbreakable end", "wait 1",}

DefineAnimations("animations-belial", {
  Still = BelialStill,
  Move = BelialMove,
  Attack = {"unbreakable begin", 
  "set-var DamageType 0 basic",
  "set-var ShieldPiercing.Value 0 0",
  "set-var LightArmorDamage.Value 0 v_LightArmorDamage2.Value",
  "set-var CombatArmorDamage.Value 0 v_CombatArmorDamage2.Value",
  "set-var HeavyArmorDamage.Value 0 v_HeavyArmorDamage2.Value",
  "set-var FleshArmorDamage.Value 0 v_FleshArmorDamage2.Value",
  "set-var HeavyFleshArmorDamage.Value 0 v_HeavyFleshArmorDamage2.Value",
  "set-var AirFleshArmorDamage.Value 0 v_AirFleshArmorDamage2.Value",
  "set-var MechanicalArmorDamage.Value 0 v_MechanicalArmorDamage2.Value",
  "set-var AirMechanicalArmorDamage.Value 0 v_AirMechanicalArmorDamage2.Value",
  "set-var BuildingArmorDamage.Value 0 v_BuildingArmorDamage2.Value",
  "set-var HeavyBuildingArmorDamage.Value 0 v_HeavyBuildingArmorDamage2.Value",
  "set-var CursedArmorDamage.Value 0 v_CursedArmorDamage2.Value",
  "frame 20", "wait 3", 
  "frame 25", "wait 3", 
  "frame 30", "attack", "sound fireball launch", "wait 3", 
  "frame 50", "wait 3", 
  "frame 35", "wait 3", 
  "frame 40", "wait 3", 
  "frame 45", "attack", "sound fireball launch", "wait 3", 
  "frame 55", "wait 3", 
  "frame 5", "wait 7",
  "unbreakable end", "wait 1",},
  SpellCast = {"unbreakable begin", 
  "if-var s_spell-belial-teleport == 1 teleport",
  "if-var s_spell-possess == 1 possess",
  "if-var s_spell-demonic-storm == 1 storm",
  "if-var s_spell-belial-vampirism == 1 vampirism",
  "frame 60", "wait 3", 
  "frame 65", "wait 3", 
  "frame 70", "wait 3", 
  "frame 75", "attack", "wait 3", 
  "frame 5", "wait 7", "goto end",
  "label teleport",
  "frame 20", "wait 30", "sound teleport", "attack", "sound teleport", "goto end",
  "label possess",
  "frame 60", "wait 3", 
  "frame 65", "wait 3", 
  "frame 70", "wait 3", 
  "frame 75", 
  "set-var VeteranOfPain.Value == 4 t",
  "set-var RessurectPlayerPain.Value == l_this t",
  "set-var ZombificationTime.Value == 400 t",
  "attack", "wait 3", 
  "frame 5", "wait 7", 
  "goto end",
  "label vampirism",
  "set-var DamageType 0 melee",
  "set-var ShieldPiercing.Value = 1",
  "set-var LightArmorDamage.Value 0 v_LightArmorDamage3.Value",
  "set-var CombatArmorDamage.Value 0 v_CombatArmorDamage3.Value",
  "set-var HeavyArmorDamage.Value 0 v_HeavyArmorDamage3.Value",
  "set-var FleshArmorDamage.Value 0 v_FleshArmorDamage3.Value",
  "set-var HeavyFleshArmorDamage.Value 0 v_HeavyFleshArmorDamage3.Value",
  "set-var AirFleshArmorDamage.Value 0 v_AirFleshArmorDamage3.Value",
  "set-var MechanicalArmorDamage.Value 0 v_MechanicalArmorDamage3.Value",
  "set-var AirMechanicalArmorDamage.Value 0 v_AirMechanicalArmorDamage3.Value",
  "set-var BuildingArmorDamage.Value 0 v_BuildingArmorDamage3.Value",
  "set-var HeavyBuildingArmorDamage.Value 0 v_HeavyBuildingArmorDamage3.Value",
  "set-var CursedArmorDamage.Value 0 v_CursedArmorDamage3.Value",
  "frame 20", "wait 3", 
  "frame 25", "wait 3", 
  "frame 30", "attack", "sound claw attack", "wait 3", 
  "frame 50", "wait 3", 
  "frame 35", "wait 3", 
  "frame 40", "wait 3", 
  "frame 45", "attack", "sound claw attack", "wait 3", 
  "frame 55", "wait 3", 
  "set-var ShieldPiercing.Value = 0",
  "goto end2",
  "label storm",
  "frame 60", "wait 3", 
  "frame 65", "wait 3", 
  "frame 70", "wait 3", 
  "frame 75", 
  "attack", 
  "set-var Op1.Value = 100", -- initial time
  "set-var Op2.Value = 30", -- addition for each level
  "set-var Op2.Value *= v_Veterancy.Value",
  "set-var Op1.Value += v_Op2.Value",
  "set-var Arg1.Value == v_Op1.Value l",
  "set-var Arg2.Value == v_Slot.Value l",
  "wait 3", 
  "frame 5", "wait 7", 
  "label end",
  
  "frame 5", "wait 17",
  "label end2",
  "unbreakable end", "wait 1",},
  Death = BelialDeath,
})

DefineAnimations("animations-belial-body", {
  Still = {"label begin","exact-frame 89","if-var v_Arg1.Value > 0 still", "exact-frame 89","wait 1", "goto end",
  "label diedemon", "die demon_eating","wait 2",
  "label still","exact-frame 89", "wait 1", 
  "if-var v_UnitFlags.Value & "..unitFlags.UF_KillFromDemon.." diedemon",
  "set-var Arg1.Value 2 1","goto begin","label end","wait 1","die","wait 2"},
  Death = {"unbreakable begin","exact-frame 89","wait 2","unbreakable end","wait 1",},
  Death_demon_eating = {"unbreakable begin","exact-frame 89","spawn-missile missile-gibs 20 20 0 0 pixel","wait 3","unbreakable end","wait 1",}
})

UnitName = "unit-belial"
BaseDamage = UnitInfo(UnitName, const.Unit_BaseDmg)
DamageType = UnitInfo(UnitName, const.Unit_DamageType)
BaseDamage2 = UnitInfo(UnitName, const.Unit_BaseDmg2)
DamageType2 = UnitInfo(UnitName, const.Unit_DamageType2)
DefineUnitType(UnitName, { Name = _("Belial"),
  -- Drawing
  Image = {"file", "graphics/hell/units/belial.png", "size", {72, 72}},
  Shadow = {"file", "graphics/hell/units/belial-s.png", "size",{72, 72},"offset", {0, 0}},
  Animations = "animations-belial", Icon = "icon-belial",
  DrawLevel = UnitInfo(UnitName, const.Unit_Draw),
  TileSize = {1, 1}, BoxSize = {47, 55}, BoxOffset = {0, -16},
  Offset = {0, -24},
  Impact = {"shell", "missile-green-shell-meat", "melee", "missile-green-melee-meat"},
  Type = "land",
  Flip = false, NumDirections = 8,
   MissileOffsets = {{{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
					{{9, 20}, {12, 21}, {13, 23}, {12, 27}, {9, 27}, {10, 28}, {10, 23}, {10, 20}},
					{{24, 20}, {22, 19}, {13, 28}, {26, 28}, {24, 27}, {23, 28}, {10, 28}, {21, 19}}},
  -- Properties
  Costs = {"time", UnitInfo(UnitName, const.Unit_Build), "minerals", UnitInfo(UnitName, const.Unit_MinCost), "energy", UnitInfo(UnitName, const.Unit_EngCost)}, 
  HitPoints = UnitInfo(UnitName, const.Unit_HP),
  RegenerationRate = 1,
  Demand = UnitInfo(UnitName, const.Unit_Supply),
  SightRange = UnitInfo(UnitName, const.Unit_Sight), ComputerReactionRange = UnitInfo(UnitName, const.Unit_Comp),
  PersonReactionRange = UnitInfo(UnitName, const.Unit_Person),
  MaxAttackRange = UnitInfo(UnitName, const.Unit_AtkRange),
  Priority = 30,
  Points = UnitInfo(UnitName, const.Unit_Points),
  Mana = UnitInfo(UnitName, const.Unit_Mana),
  ArtifactGive = UnitInfo(UnitName, const.Unit_Artifact),
  PoisonDrain = 1,
  ShieldPiercing = {Value = 0, Max = 1, Enable = true, Increase = 0},
  CanCastSpell = {"spell-possess", "spell-demonic-storm-for-ai", "spell-demonic-storm",  "spell-rage", "spell-belial-teleport", 
	 "spell-belial-vampirism"},
  -- Damage and armor part
  BasicDamage = 1, PiercingDamage = 1, Missile = "missile-slowball",
  IsHeavyFleshArmor = 1,
  BaseDamage = BaseDamage,
  BaseDamage2 = BaseDamage2,

  LightArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 1),
  CombatArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 2),
  HeavyArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 3),
  
  FleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 4),
  HeavyFleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 5),
  AirFleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 6),
  
  MechanicalArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 7),
  AirMechanicalArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 8),
  
  BuildingArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 9),
  HeavyBuildingArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, 10),
  
  CursedArmorDamage2 = GetCursedDamage(BaseDamage),
  
  LightArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 1),
  CombatArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 2),
  HeavyArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 3),
  
  FleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 4),
  HeavyFleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 5),
  AirFleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 6),
  
  MechanicalArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 7),
  AirMechanicalArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 8),
  
  BuildingArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 9),
  HeavyBuildingArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, 10),
  
  CursedArmorDamage3 = GetCursedDamage(BaseDamage2),
  ----------------------
  -- Flags
  Hell = true,
  HeavyFlesh = true,
  CanAttack = true,
  CanTargetAir = true,
  CanTargetLand = true,
  LandUnit = true,
  ShowArmor = true,
  organic = true,
  SelectableByRectangle = true,
  -- Other
  OnEachSecond = UpdateVeteranStatus,
  RightMouseAction = "attack",
  Sounds = {
    "selected", "belial-selected",
    "acknowledge", "belial-acknowledge",
	"attack", "belial-attack",
    "ready", "belial-ready",
    "help", "hell unit under attack",
    "dead", "belial death"} } )

DefineUnitType("unit-belial-body", { Name = _("Belial Body"),
  Image = {"file", "graphics/hell/units/belial.png", "size", {72, 72}},
  Animations = "animations-belial-body", Icon = "icon-belial",
  HitPoints = 150,
  Offset = {0, -20},
  DrawLevel = 10,
  Indestructible = 1,
  IsHeavyFleshArmor = 1,
  NumDirections = 8, Flip = false,
  NoRandomPlacing = true,
  TileSize = {1, 1}, BoxSize = {31, 31},
  SightRange = 0,
  Arg1 = 3600,
  BasicDamage = 0, PiercingDamage = 0, Missile = "missile-none",
  Priority = 0,
  Type = "land",
  NonSolid = true,
  Hell = true,
  Dead = true,
  IsNotSelectable = true,
  Sounds = {} } )