-- Some variables to make calculations much easier
local UnitName
local BaseDamage = 0
local BaseDamage2 = 0
local BaseDamage3 = 0
local DamageType
local DamageType2
local DamageType3

local MancubusStill = {"frame 10", "wait 4", "random-goto 99 no-rotate","frame 15", "wait 4","frame 20", "wait 4", 
"frame 25", "wait 4","frame 0", "wait 4","frame 5", "wait 4","random-rotate 1", "label no-rotate", "wait 1",}
local MancubusMove = {"unbreakable begin",
	"if-var v_HitPoints.Percent <= 40 damaged40", 
	"frame 0", "move 3", "wait 3", 
	"frame 0", "move 3", "wait 2",
    "frame 5", "move 3", "wait 3", 
	"frame 5", "move 3", "wait 2",
    "frame 10", "move 3", "wait 3", 
	"frame 10", "move 3", "wait 2",
	"frame 15", "move 2", "wait 3", 
	"frame 15", "move 2", "wait 2",
    "frame 20", "move 3", "wait 3", 
	"frame 20", "move 3", "wait 2",
    "frame 25", "move 2", "wait 3", 
	"frame 25", "move 2", "wait 2", "goto end",
	"label damaged40",
	"frame 0", "move 3", "wait 3", 
	"frame 0", "move 3", "wait 3",
    "frame 5", "move 3", "wait 3", 
	"frame 5", "move 3", "wait 3",
    "frame 10", "move 3", "wait 3", 
	"frame 10", "move 3", "wait 3",
	"frame 15", "move 2", "wait 3", 
	"frame 15", "move 2", "wait 3",
    "frame 20", "move 3", "wait 3", 
	"frame 20", "move 3", "wait 3",
    "frame 25", "move 2", "wait 3", 
	"frame 25", "move 2", "wait 3",
    "label end", "unbreakable end", "wait 1",}
local MancubusDeath = {"unbreakable begin", 
	"exact-frame 45", "spawn-missile missile-gibs 20 20 0 0 pixel", "wait 3", 
	"exact-frame 46", "wait 3", 
	"exact-frame 47", "wait 3", 
	"exact-frame 48", "wait 3", 
	"exact-frame 49", "wait 3", 
	"exact-frame 50", "wait 3", 
	"exact-frame 51", "wait 3", 
	"exact-frame 52", "wait 3", 
	"exact-frame 53", "wait 3", 
	"exact-frame 54", "spawn-unit unit-mancubus-body 0 0 2 15 summoned", 
	"set-var ArtifactGive.Max 0 v_ArtifactGive.Value l",
		"set-var ArtifactGive.Value 0 v_ArtifactGive.Value l",
		"set-var ArtifactGive.Enable 0 1 l",
		"set-var RessurectPlayer.Value 0 l_this l", "wait 3",
	"unbreakable end", "wait 1",}

DefineAnimations("animations-mancubus-body", {
  Still = {"label begin","exact-frame 54","if-var v_Arg1.Value > 0 still", "exact-frame 54","wait 1", "goto end", 
  "label ressurect", 
  "set-var UnitFlags.Value &= "..unitFlags.UF_Raising,
  "sound vgavnonah", 
  "exact-frame 54","wait 3",
  "exact-frame 53","wait 3",
  "exact-frame 52","wait 3",
  "exact-frame 51","wait 3",
  "exact-frame 50","wait 3",
  "exact-frame 49", "wait 3", 
  "exact-frame 48", "wait 3", 
  "exact-frame 47", "wait 3", 
  "exact-frame 46", "wait 3", 
  "exact-frame 45", "wait 3",
  "spawn-unit unit-mancubus 0 0 2 v_RessurectPlayer.Value jointoai.summoned", "goto end",
  "label diedemon", "die demon_eating","wait 2",	
  "label still","exact-frame 54", "wait 1", 
  "if-var v_UnitFlags.Value & "..unitFlags.UF_KillFromDemon.." diedemon",
  "if-var v_Ressurect.Value >= v_NeedToResurrect.Value ressurect", 
  "set-var Arg1.Value 2 1","goto begin","label end","die ressurect","wait 2"},
  Death = {"unbreakable begin","exact-frame 54","wait 2","unbreakable end","wait 1",},
  Death_ressurect = {"unbreakable begin","exact-frame 54","unbreakable end","wait 1",},
  Death_demon_eating = {"unbreakable begin","exact-frame 54","spawn-missile missile-gibs 20 20 0 0 pixel","wait 3","unbreakable end","wait 1",}
})
	
DefineAnimations("animations-mancubus", {
  Still = MancubusStill,
  Move = MancubusMove,
  Attack = {"unbreakable begin", 
  "frame 30", "sound mancubus attack", "wait 15", 
  "if-var v_Veterancy.Value != 4 normal",
  "frame 35", "rotate target", "spawn-missile missile-mancubus-fire-elite 0 0 0 0 damage.totarget 1", "sound fireball launch", 
		"spawn-missile missile-mancubus-fire-elite 0 0 r_-1.1 r_-1.1 damage.totarget 2", "wait 7", 
  "frame 40", "wait 2", "rotate target",
  "frame 30", "wait 2", 
  "frame 35", "rotate target", "spawn-missile missile-mancubus-fire-elite 0 0 r_-1.1 r_-1.1 damage.totarget 1", "sound fireball launch", 
		"spawn-missile missile-mancubus-fire-elite 0 0 0 0 damage.totarget 2", "wait 7", 
  "frame 40", "wait 2", "rotate target",
  "frame 30", "wait 2", 
  "frame 35", "rotate target", "spawn-missile missile-mancubus-fire-elite 0 0 r_-1.1 r_-1.1 damage.totarget 1", "sound fireball launch", 
	"spawn-missile missile-mancubus-fire-elite 0 0 r_-1.1 r_-1.1 damage.totarget 2", "wait 7", 
  "frame 40", "wait 2", "rotate target",
  "frame 30", "rotate target", "wait 2",
  "goto end",
  "label normal",
  "frame 35", "rotate target", "spawn-missile missile-mancubus-fire 0 0 0 0 damage.totarget 1", "sound fireball launch", 
		"spawn-missile missile-mancubus-fire 0 0 r_-1.1 r_-1.1 damage.totarget 2", "wait 7", 
  "frame 40", "wait 2", "rotate target",
  "frame 30", "wait 2", 
  "frame 35", "rotate target", "spawn-missile missile-mancubus-fire 0 0 r_-1.1 r_-1.1 damage.totarget 1", "sound fireball launch", 
		"spawn-missile missile-mancubus-fire 0 0 0 0 damage.totarget 2", "wait 7", 
  "frame 40", "wait 2", "rotate target",
  "frame 30", "wait 2", 
  "frame 35", "rotate target", "spawn-missile missile-mancubus-fire 0 0 r_-1.1 r_-1.1 damage.totarget 1", "sound fireball launch", 
	"spawn-missile missile-mancubus-fire 0 0 r_-1.1 r_-1.1 damage.totarget 2", "wait 7", 
  "frame 40", "wait 2", "rotate target",
  "frame 30", "wait 2",
  "label end",
  "frame 0", "wait 30",
  "frame 0", "unbreakable end", "wait 1",},  
  Death = MancubusDeath,
})

UnitName = "unit-mancubus"
BaseDamage = UnitInfo(UnitName, const.Unit_BaseDmg)
DamageType = UnitInfo(UnitName, const.Unit_DamageType)
DefineUnitType(UnitName, { Name = _("Mancubus"),
  -- Drawing
  Image = {"file", "graphics/hell/units/mancubus.png", "size", {80, 80}},
  Animations = "animations-mancubus", Icon = "icon-mancubus",
  Shadow = {"file", "graphics/hell/units/mancubus-s.png", "size",{80, 80},"offset", {0, 0}},
  Flip = false, NumDirections = 8,
  DrawLevel = UnitInfo(UnitName, const.Unit_Draw),
  Offset = {0, -24},
  Type = "land",
  TileSize = {1, 1}, BoxSize = {70, 60}, BoxOffset = {0, -4},
  Impact = {"shell", "missile-red-shell-meat", "melee", "missile-red-melee-meat"},
  MissileOffsets = {{{-20, -10}, {14, -20}, {28, -10}, {40, 0}, {25, 10}, {-10, 8}, {-16, -4}, {-36, -10}},
					{{25, -10}, {32, -15}, {36, -5}, {8, 8}, {-20, 10}, {-38, 4}, {-16, -8}, {0, -10}}},
  -- Properties
  Costs = {"time", UnitInfo(UnitName, const.Unit_Build), "minerals", UnitInfo(UnitName, const.Unit_MinCost), "energy", UnitInfo(UnitName, const.Unit_EngCost)},
  HitPoints = UnitInfo(UnitName, const.Unit_HP),
  SightRange = UnitInfo(UnitName, const.Unit_Sight), ComputerReactionRange = UnitInfo(UnitName, const.Unit_Comp),
  PersonReactionRange = UnitInfo(UnitName, const.Unit_Person),
  MaxAttackRange = UnitInfo(UnitName, const.Unit_AtkRange),
  Priority = 30,
  Points = UnitInfo(UnitName, const.Unit_Points),
  Demand = UnitInfo(UnitName, const.Unit_Supply),
  PoisonDrain = 1,
  DamageType = "fire",
  ArtifactGive = UnitInfo(UnitName, const.Unit_Artifact),
  -- Damage and armor part
  BasicDamage = 1, PiercingDamage = 1, Missile = "missile-mancubus-fire",
  IsHeavyFleshArmor = 1,
  BaseDamage = BaseDamage,

  LightArmorDamage = GetArmorDamage(BaseDamage, DamageType, 1),
  CombatArmorDamage = GetArmorDamage(BaseDamage, DamageType, 2),
  HeavyArmorDamage = GetArmorDamage(BaseDamage, DamageType, 3),
  
  FleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 4),
  HeavyFleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 5),
  AirFleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 6),
  
  MechanicalArmorDamage = GetArmorDamage(BaseDamage, DamageType, 7),
  AirMechanicalArmorDamage = GetArmorDamage(BaseDamage, DamageType, 8),
  
  BuildingArmorDamage = GetArmorDamage(BaseDamage, DamageType, 9),
  HeavyBuildingArmorDamage = GetArmorDamage(BaseDamage, DamageType, 10),
  
  CursedArmorDamage = GetCursedDamage(BaseDamage),
  ----------------------
  -- Flags
  HeavyFlesh = true,
  Hell = true,
  CanAttack = true,
  -- CanGroundAttack = true,
  GroundAttack = true,
  CanTargetLand = true,
  CanTargetSea = true,
  LandUnit = true,
  ShowArmor = true,
  organic = true,
  SelectableByRectangle = true,
  -- Other
  OnEachSecond = UpdateVeteranStatus,
  RightMouseAction = "attack",
  PriorityTarget = {"organic", "only", "Mechanical", "false", "AirUnit", "false", "Building", "only"},
  Sounds = {
    "selected", "mancubus sight",
    "acknowledge", "zombie move",
    "ready", "mancubus sight",
    "help", "hell unit under attack",
    "dead", "mancubus death"} } )
	
DefineUnitType("unit-mancubus-body", { Name = _("Mancubus Body"),
  Image = {"file", "graphics/hell/units/mancubus.png", "size", {80, 80}},
  Animations = "animations-mancubus-body", Icon = "icon-mancubus",
  HitPoints = 200,
  DrawLevel = 10,
  Offset = {0, -24},
  Indestructible = 1,
  IsHeavyFleshArmor = 1,
  NeedToResurrect = 5,
  NumDirections = 8, Flip = false,
  NoRandomPlacing = true,
  IsResurrectable = true,
  TileSize = {1, 1}, BoxSize = {31, 31},
  SightRange = 0,
  Arg1 = 3600,
  BasicDamage = 0, PiercingDamage = 0, Missile = "missile-none",
  Priority = 0,
  Type = "land",
  NonSolid = true,
  Hell = true,
  Dead = true,
  IsNotSelectable = true,
  Sounds = {} } )
