-- Some variables to make calculations much easier
local UnitName
local BaseDamage = 0
local BaseDamage2 = 0
local BaseDamage3 = 0
local DamageType
local DamageType2
local DamageType3

local CacoStill = UnitStill
local CacoMove = {"unbreakable begin", 
	"if-var v_UnitFlags.Value & "..unitFlags.UF_UpgradeSpeed.." speedup",
	"if-var v_HitPoints.Percent <= 40 damaged40", 
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
    "frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1", "goto end",
	"label damaged40",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2",
    "frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 2", "goto end",
	"label speedup",
	"if-var v_HitPoints.Percent <= 40 speedup40", 
	"frame 0", "move 3", "wait 1", 
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 3", "wait 1",
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", "goto end",
	"label speedup40",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
    "frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1",
	"label end", "unbreakable end", "wait 1"}
local CacoDeath = {"unbreakable begin", 
	"exact-frame 20", "spawn-missile missile-blue-gibs 0 20 0 0 pixel", "wait 4", 
	"exact-frame 21", "wait 4", 
	"exact-frame 22", "wait 4", 
	"exact-frame 23", "wait 4", 
	"exact-frame 24", "wait 4", 
	"exact-frame 25", "spawn-unit unit-cacodemon-body 0 0 2 15 summoned", 
	"set-var ArtifactGive.Max 0 v_ArtifactGive.Value l",
		"set-var ArtifactGive.Value 0 v_ArtifactGive.Value l",
		"set-var ArtifactGive.Enable 0 1 l",
		"set-var RessurectPlayer.Value 0 l_this l", 
    "unbreakable end","wait 1",}
	
DefineAnimations("animations-cacodemon-body", {
  Still = {"label begin","exact-frame 25","if-var v_Arg1.Value > 0 still", "exact-frame 25","wait 1", "goto end", 
  "label ressurect", 
  "set-var UnitFlags.Value &= "..unitFlags.UF_Raising,
  "sound vgavnonah", 
  "exact-frame 25","wait 4",
  "exact-frame 24","wait 4",
  "exact-frame 23","wait 4",
  "exact-frame 22","wait 4",
  "exact-frame 21","wait 4",
  "exact-frame 20", "wait 4", 
  "spawn-unit unit-cacodemon 0 0 2 v_RessurectPlayer.Value jointoai.summoned", "goto end",
  "label diedemon", "die demon_eating","wait 2",	
  "label still","exact-frame 25", "wait 1", 
  "if-var v_UnitFlags.Value & "..unitFlags.UF_KillFromDemon.." diedemon",
  "if-var v_Ressurect.Value >= v_NeedToResurrect.Value ressurect", 
  "set-var Arg1.Value 2 1","goto begin","label end","die ressurect","wait 2"},
  Death = {"unbreakable begin","exact-frame 25","wait 2","unbreakable end","wait 1",},
  Death_ressurect = {"unbreakable begin","exact-frame 25","unbreakable end","wait 1",},
  Death_demon_eating = {"unbreakable begin","exact-frame 25","spawn-missile missile-gibs 20 20 0 0 pixel","wait 3","unbreakable end","wait 1",}
})

DefineAnimations("animations-cacodemon", {
  Still = CacoStill,
  Move = CacoMove,
  Attack = {"unbreakable begin", 
  "frame 0", "wait 3", 
  "frame 5", "wait 3",
  "frame 10", "wait 3", 
  "frame 15", 
  "if-var v_UnitFlags.Value & "..unitFlags.UF_UpgradeCacoBall.." airfire",
  "spawn-missile missile-caco-ball 0 0 r_0.0 r_0.0 damage.totarget",
  "if-var v_Veterancy.Value != 4 endfire",
  "spawn-missile missile-caco-ball 0 0 r_-1.1 r_-1.1 damage.totarget",
  "spawn-missile missile-caco-ball 0 0 r_-1.1 r_-1.1 damage.totarget",
  "goto endfire",
  "label airfire",
  "spawn-missile missile-caco-ball-air 0 0 0 0 damage.totarget",
  "if-var v_Veterancy.Value != 4 endfire",
  "spawn-missile missile-caco-ball-air 0 0 r_-1.1 r_-1.1 damage.totarget",
  "spawn-missile missile-caco-ball-air 0 0 r_-1.1 r_-1.1 damage.totarget",
  "label endfire",
  "sound fireball launch", "wait 8",
  "frame 0", "wait 10", 
    "unbreakable end", "wait 1"},
  Death = CacoDeath
})

UnitName = "unit-cacodemon"
BaseDamage = UnitInfo(UnitName, const.Unit_BaseDmg)
DamageType = UnitInfo(UnitName, const.Unit_DamageType)
DefineUnitType(UnitName, { Name = _("Cacodemon"),
  -- Drawing
  Image = {"file", "graphics/hell/units/caco.png", "size", {56, 56}},
  Shadow = {"file", "graphics/hell/units/caco-s.png", "size",{56, 56},"offset", {24, 24}},
  Animations = "animations-cacodemon", Icon = "icon-cacodemon",
  DrawLevel = UnitInfo(UnitName, const.Unit_Draw),
  TileSize = {1, 1}, BoxSize = {49, 49},
  Impact = {"shell", "missile-blue-shell-meat", "melee", "missile-blue-melee-meat"},
  MissileOffsets = {{{0, 0}, {6, 3}, {21, 0}, {7, 9}, {0, 5}, {-11, 11}, {-19, 5}, {-10, 6}}},
  Flip = false, NumDirections = 8,
  Type = "fly",
  -- Properties
  Costs = {"time", UnitInfo(UnitName, const.Unit_Build), "minerals", UnitInfo(UnitName, const.Unit_MinCost), "energy", UnitInfo(UnitName, const.Unit_EngCost)},
  HitPoints = UnitInfo(UnitName, const.Unit_HP),
  PoisonDrain = 1,
  SightRange = UnitInfo(UnitName, const.Unit_Sight), ComputerReactionRange = UnitInfo(UnitName, const.Unit_Comp),
  PersonReactionRange = UnitInfo(UnitName, const.Unit_Person),
  MaxAttackRange = UnitInfo(UnitName, const.Unit_AtkRange),
  Priority = 30,
  Demand = UnitInfo(UnitName, const.Unit_Supply),
  Points = UnitInfo(UnitName, const.Unit_Points),
  ArtifactGive = UnitInfo(UnitName, const.Unit_Artifact),
  -- Damage and armor part
  BasicDamage = 1, PiercingDamage = 1, Missile = "missile-caco-ball",
  IsAirFleshArmor = 1,
  BaseDamage = BaseDamage,

  LightArmorDamage = GetArmorDamage(BaseDamage, DamageType, 1),
  CombatArmorDamage = GetArmorDamage(BaseDamage, DamageType, 2),
  HeavyArmorDamage = GetArmorDamage(BaseDamage, DamageType, 3),
  
  FleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 4),
  HeavyFleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 5),
  AirFleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 6),
  
  MechanicalArmorDamage = GetArmorDamage(BaseDamage, DamageType, 7),
  AirMechanicalArmorDamage = GetArmorDamage(BaseDamage, DamageType, 8),
  
  BuildingArmorDamage = GetArmorDamage(BaseDamage, DamageType, 9),
  HeavyBuildingArmorDamage = GetArmorDamage(BaseDamage, DamageType, 10),
  
  CursedArmorDamage = GetCursedDamage(BaseDamage),
  ----------------------
  -- Flags
  Hell = true,
  CanAttack = true,
  CanTargetLand = true,
  CanTargetSea = true,
  CanTargetAir = true,
  AirUnit = true,
  ShowArmor = true,
  organic = true,
  SelectableByRectangle = true,
  -- Other
  PriorityTarget = {"organic", "false", "AirUnit", "only", "Mechanical", "only", "Building", "only"},
  OnEachSecond = UpdateVeteranStatus,
  RightMouseAction = "attack",
  Sounds = {
    "selected", "cacodemon-select",
    "acknowledge", "demons-move",
    "ready", "cacodemon-select",
    "help", "hell unit under attack",
    "dead", "cacodemon-death"} } )
	
DefineUnitType("unit-cacodemon-body", { Name = _("Cacodemon Body"),
  Image = {"file", "graphics/hell/units/caco.png", "size", {56, 56}},
  Animations = "animations-cacodemon-body", Icon = "icon-cacodemon",
  HitPoints = 150,
  DrawLevel = 10,
  IsHeavyFleshArmor = 1,
  Indestructible = 1,
  NeedToResurrect = 4,
  NumDirections = 8, Flip = false,
  NoRandomPlacing = true,
  IsResurrectable = true,
  TileSize = {1, 1}, BoxSize = {31, 31},
  SightRange = 0,
  Arg1 = 3600,
  BasicDamage = 0, PiercingDamage = 0, Missile = "missile-none",
  Priority = 0,
  Type = "land",
  NonSolid = true,
  Hell = true,
  Dead = true,
  IsNotSelectable = true,
  Sounds = {} } )