-- Some variables to make calculations much easier
local UnitName
local BaseDamage = 0
local BaseDamage2 = 0
local BaseDamage3 = 0
local DamageType
local DamageType2
local DamageType3

local PlasmaStill = {"set-var Repair.Value 0 0", "frame 5", "wait 4", "random-goto 99 no-rotate", "frame 10", "wait 4",
"frame 15", "wait 4","frame 0", "wait 4","random-rotate 1", "label no-rotate", "wait 1",}
local PlasmaMove = {"unbreakable begin",
	"set-var Repair.Value 0 1",
	"frame 0", "if-var v_HitPoints.Percent <= 40 damaged50",
	"frame 0", "move 2", "wait 1",
	"frame 0", "move 2", "wait 1",
	"frame 5", "move 2", "wait 1",
	"frame 5", "move 2", "wait 1",
    "frame 10", "move 2", "wait 1", 
	"frame 10", "move 2", "wait 1",
	"frame 15", "move 2", "wait 1", 
	"frame 15", "move 2", "wait 1",
    "frame 0", "move 2", "wait 1", 
	"frame 0", "move 2", "wait 1", 
	"frame 5", "move 2", "wait 1", 
	"frame 5", "move 2", "wait 1",
    "frame 10", "move 2", "wait 1", 
	"frame 10", "move 2", "wait 1",
	"frame 15", "move 2", "wait 1", 
	"frame 15", "move 2", "wait 1", "goto end",
	"label damaged50",
	"frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 1", 
	"frame 5", "move 2", "wait 2", 
	"frame 5", "move 2", "wait 1",
    "frame 10", "move 2", "wait 2", 
	"frame 10", "move 2", "wait 1",
	"frame 15", "move 2", "wait 2", 
	"frame 15", "move 2", "wait 1",
    "frame 0", "move 2", "wait 2", 
	"frame 0", "move 2", "wait 1", 
	"frame 5", "move 2", "wait 2", 
	"frame 5", "move 2", "wait 1",
    "frame 10", "move 2", "wait 2", 
	"frame 10", "move 2", "wait 1",
	"frame 15", "move 2", "wait 2", 
	"frame 15", "move 2", "wait 1", "goto end",
	"label end","unbreakable end", "wait 1",}
local PlasmaDeath = {"unbreakable begin", 
	"frame 30", "spawn-missile missile-gibs 20 20 0 0 pixel", "wait 3", 
	"frame 35", "wait 3", 
	"frame 40", "wait 3", 
	"frame 45", "wait 3", 
	"frame 50", "wait 3", 
	"frame 55", "wait 3", 
	"frame 60", "spawn-unit unit-plasmamarine-body 0 0 2 15", "set-var RessurectPlayer.Value 0 l_this l",
	"if-var v_UsedSpheres.Value & "..marineSpheres.S_Skull.." skull",
	"if-var v_ZombificationTime.Value == 0 normal",
	"if-var v_VeteranOfPain.Value == 4 elite",
	"if-var r_100 >= 33 normal",
	"label elite",
	"set-var RessurectPlayer.Value 0 v_RessurectPlayerPain.Value l",
	"set-var Ressurect.Value 0 5 l",
	"goto normal",
	"label skull",
	"set-var UsedSpheres.Value += "..marineSpheres.S_Skull.." l",
	"label normal",
    "frame 60", "unbreakable end", "wait 1",}
local PlasmaDeathExtreme = {"unbreakable begin", 
	"frame 65", "spawn-missile missile-extreme-gibs 20 20 0 0 pixel", "spawn-missile missile-gibs 20 20 0 0 pixel", "wait 3", 
	"frame 70", "wait 3", 
	"frame 75", "wait 3", 
	"frame 80", "wait 3", 
	"frame 85", "wait 3", 
	"frame 90", "wait 3",
	"frame 95", "wait 3",
	"frame 100", "wait 3",
	"frame 105", "wait 2000",
    "frame 105", "unbreakable end", "wait 1",}

DefineAnimations("animations-plasmamarine-body", {
  Still = {"label begin","frame 60","if-var v_Arg1.Value > 0 still", "frame 60","wait 1", "goto end", 
  "label ressurect", 
  "spawn-unit unit-zombie-plasma-body 0 0 2 v_RessurectPlayer.Value jointoai", "set-var RessurectPlayer.Value 0 v_RessurectPlayer.Value l", "set-var Ressurect.Value 0 2 l", "goto end",
  "label defibrillation",
  "spawn-unit unit-plasmamarine 0 0 2 v_RessurectPlayer.Value",
  "set-var HitPoints.Percent 0 30 l",
  "set-var ShieldPoints.Value == 0 l",
  "goto end",
  "label diedemon", "die demon_eating","wait 2",
  "label still","frame 60", "wait 1", 
  "if-var v_UnitFlags.Value & "..unitFlags.UF_KillFromDemon.." diedemon",
  "if-var v_Ressurect.Value >= 1 ressurect", 
  "if-var v_DoneDefibrillation.Value == 1 defibrillation",
  "set-var Arg1.Value 2 1","goto begin","label end","wait 1","die ressurect","wait 2"},
  Death_demon_eating = {"unbreakable begin","frame 60","spawn-missile missile-gibs 20 20 0 0 pixel","wait 3","unbreakable end","wait 1",},
  Death = {"unbreakable begin","frame 60","unbreakable end","wait 1",}
})

DefineAnimations("animations-plasmamarine", {
  Still = PlasmaStill,
  Move = PlasmaMove,
  Attack = {"unbreakable begin", 
  "set-var Repair.Value 0 1",
  "frame 20", "wait 1", 
  "frame 25", "attack", "sound plasma shot",
  "if-var v_Veterancy.Value != 4 normal",
  "wait 2", "goto end",
  "label normal",
  "wait 3", "label end",
  "frame 25", 
  "unbreakable end", "wait 1",},
  Death = PlasmaDeath,
  Death_extreme = PlasmaDeathExtreme,
  Death_fire = {"unbreakable begin","frame 110","spawn-unit unit-burning 0 0 5 15","wait 100","unbreakable end","wait 1",},
})

UnitName = "unit-plasmamarine"
BaseDamage = UnitInfo(UnitName, const.Unit_BaseDmg)
DamageType = UnitInfo(UnitName, const.Unit_DamageType)
DefineUnitType(UnitName, { Name = _("Heavy Trooper"),
  -- Drawing
  Image = {"file", "graphics/uac/units/plasmagunner.png", "size", {42, 42}},
  Shadow = {"file", "graphics/uac/units/plasmagunner-s.png", "size",{42, 42},"offset", {0, 0}},
  Animations = "animations-plasmamarine", Icon = "icon-plasmamarine",
  DrawLevel = UnitInfo(UnitName, const.Unit_Draw),
  TileSize = {1, 1}, BoxSize = {30, 45},
  MissileOffsets = {{{8, -12}, {13, -9}, {16, -6}, {19, -3}, {-13, -6}, {-16, -6}, {-20, -4}, {-14, -3}}},
  Impact = {"shell", "missile-red-shell-meat", "melee", "missile-red-melee-meat"},
  Type = "land",
  Flip = false, NumDirections = 8,
  -- Properties
  Costs = {"time", UnitInfo(UnitName, const.Unit_Build), "minerals", UnitInfo(UnitName, const.Unit_MinCost), "energy", UnitInfo(UnitName, const.Unit_EngCost)},
  HitPoints = UnitInfo(UnitName, const.Unit_HP),
  ShieldPoints = {Value = UnitInfo(UnitName, const.Unit_SP), Max = UnitInfo(UnitName, const.Unit_SP), Increase = 0, Enable = ShieldEnableControl(UnitInfo(UnitName, const.Unit_SP))},
  SightRange = UnitInfo(UnitName, const.Unit_Sight), ComputerReactionRange = UnitInfo(UnitName, const.Unit_Comp),
  PersonReactionRange = UnitInfo(UnitName, const.Unit_Person),
  MaxAttackRange = UnitInfo(UnitName, const.Unit_AtkRange),
  Priority = 30,
  ShieldPermeability = 30,
  Points = UnitInfo(UnitName, const.Unit_Points),
  PoisonDrain = 1,
  Demand = UnitInfo(UnitName, const.Unit_Supply),
  DamageType = "fire",
  -- Damage and armor part
  BasicDamage = 1, PiercingDamage = 1, Missile = "missile-plasmaball",
  IsCombatArmor = 1,
  BaseDamage = BaseDamage,

  LightArmorDamage = GetArmorDamage(BaseDamage, DamageType, 1),
  CombatArmorDamage = GetArmorDamage(BaseDamage, DamageType, 2),
  HeavyArmorDamage = GetArmorDamage(BaseDamage, DamageType, 3),
  
  FleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 4),
  HeavyFleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 5),
  AirFleshArmorDamage = GetArmorDamage(BaseDamage, DamageType, 6),
  
  MechanicalArmorDamage = GetArmorDamage(BaseDamage, DamageType, 7),
  AirMechanicalArmorDamage = GetArmorDamage(BaseDamage, DamageType, 8),
  
  BuildingArmorDamage = GetArmorDamage(BaseDamage, DamageType, 9),
  HeavyBuildingArmorDamage = GetArmorDamage(BaseDamage, DamageType, 10),
  
  CursedArmorDamage = GetCursedDamage(BaseDamage),
  ----------------------
  -- Flags
  ArmorShield = 1,
  UAC = true,
  CanAttack = true,
  ShowArmor = true,
  CanTargetLand = true,
  CanTargetAir = true,
  LandUnit = true,
  BigUnit = true,
  organic = true,
  SelectableByRectangle = true,
  SphereMarine = true,
  -- Other
  RightMouseAction = "attack",
  OnEachSecond = UpdateVeteranStatus,
  OnHit = MarineInvulnSphereHit,
  PriorityTarget = {"AirUnit", "false", "LandUnit", "only"},
  Sounds = {
    "selected", "plasmamarine-selected",
    "acknowledge", "plasmamarine-acknowledge",
	"attack", "plasmamarine-attack",
    "ready", "plasmamarine-ready",
    "help", "uac unit under attack",
	"dead", "extreme","vgavnonah",
	"dead", "fire","marine fire death",
    "dead", "uac marine death"} } )

DefineUnitType("unit-plasmamarine-body", { Name = _("Heavy Trooper Body"),
  Image = {"file", "graphics/uac/units/plasmagunner.png", "size", {42, 42}},
  Animations = "animations-plasmamarine-body", Icon = "icon-cancel",
  HitPoints = 100,
  DrawLevel = 10,
  IsHeavyFleshArmor = 1,
  Indestructible = 1,
  NumDirections = 8, Flip = false,
  NoRandomPlacing = true,
  TileSize = {1, 1}, BoxSize = {31, 31},
  SightRange = 0,
  Arg1 = 3600,
  OnEachCycle = HandleDefibrillation,
  BasicDamage = 0, PiercingDamage = 0, Missile = "missile-none",
  Priority = 0,
  Type = "land",
  NonSolid = true,
  UAC = true,
  Dead = true,
  IsNotSelectable = true,
  Sounds = {} })