-- Some variables to make calculations much easier
local UnitName
local BaseDamage = 0
local BaseDamage2 = 0
local BaseDamage3 = 0
local DamageType
local DamageType2
local DamageType3

local HeroStill = { 
	"frame 5", "if-var v_Weapon.Value == 0 quad",
	"if-var v_Weapon.Value == 2 unmaker",
	"frame 25", "wait 4", "random-goto 99 no-rotate", 
	"frame 30", "wait 4",
	"frame 35", "wait 4",
	"frame 20", "wait 4","random-rotate 1", "goto no-rotate",
	"label quad",
	"frame 5", "wait 4", "random-goto 99 no-rotate", 
	"frame 10", "wait 4",
	"frame 15", "wait 4",
	"frame 0", "wait 4","random-rotate 1", "goto no-rotate",
	"label unmaker",
	"frame 95", "wait 4", "random-goto 99 no-rotate", 
	"frame 100", "wait 4",
	"frame 105", "wait 4",
	"frame 90", "wait 4","random-rotate 1",
	"label no-rotate", "wait 1",}
local HeroMove = {"unbreakable begin",
	"frame 0", "if-var v_Weapon.Value == 0 prepquad",
	"if-var v_Weapon.Value == 2 prepunm",
	"set-var Arg12.Value 0 20",
	"set-var Arg13.Value 0 25",
	"set-var Arg14.Value 0 30",
	"set-var Arg15.Value 0 35", "goto go",
	"label prepquad",
	"set-var Arg12.Value 0 0",
	"set-var Arg13.Value 0 5",
	"set-var Arg14.Value 0 10",
	"set-var Arg15.Value 0 15", "goto go",
	"label prepunm",
	"set-var Arg12.Value 0 90",
	"set-var Arg13.Value 0 95",
	"set-var Arg14.Value 0 100",
	"set-var Arg15.Value 0 105",
	"label go",
	"frame v_Arg12.Value", "if-var v_HitPoints.Percent <= 40 damaged50",
	"frame v_Arg12.Value", "move 2", "wait 1", 
	"frame v_Arg12.Value", "move 2", "wait 1", 
	"frame v_Arg13.Value", "move 2", "wait 1", 
	"frame v_Arg13.Value", "move 2", "wait 1", 
    "frame v_Arg14.Value", "move 2", "wait 1", 
	"frame v_Arg14.Value", "move 2", "wait 1", 
	"frame v_Arg15.Value", "move 2", "wait 1", 
	"frame v_Arg15.Value", "move 2", "wait 1", 
    "frame v_Arg12.Value", "move 2", "wait 1", 
	"frame v_Arg12.Value", "move 2", "wait 1", 
	"frame v_Arg13.Value", "move 2", "wait 1", 
	"frame v_Arg13.Value", "move 2", "wait 1", 
    "frame v_Arg14.Value", "move 2", "wait 1", 
	"frame v_Arg14.Value", "move 2", "wait 1", 
	"frame v_Arg15.Value", "move 2", "wait 1",
	"frame v_Arg15.Value", "move 2", "goto end",
	"label damaged50",
	"frame v_Arg12.Value", "move 2", "wait 1", 
	"frame v_Arg12.Value", "move 2", "wait 2", 
	"frame v_Arg13.Value", "move 2", "wait 1", 
	"frame v_Arg13.Value", "move 2", "wait 2",
    "frame v_Arg14.Value", "move 2", "wait 1", 
	"frame v_Arg14.Value", "move 2", "wait 2",
	"frame v_Arg15.Value", "move 2", "wait 1", 
	"frame v_Arg15.Value", "move 2", "wait 2",
    "frame v_Arg12.Value", "move 2", "wait 1", 
	"frame v_Arg12.Value", "move 2", "wait 2", 
	"frame v_Arg13.Value", "move 2", "wait 1", 
	"frame v_Arg13.Value", "move 2", "wait 2",
    "frame v_Arg14.Value", "move 2", "wait 1", 
	"frame v_Arg14.Value", "move 2", "wait 2",
	"frame v_Arg15.Value", "move 2", "wait 1",
	"frame v_Arg15.Value", "move 2", "wait 2",
	"label end","unbreakable end", "wait 1",}
local HeroDeath = {"unbreakable begin", 
	"exact-frame 70", "wait 3",
	"exact-frame 71", "wait 3",
	"exact-frame 72", "wait 3",
	"exact-frame 73", "wait 3",
	"exact-frame 74", "wait 3",
	"exact-frame 75", "wait 3",
	"exact-frame 76", "spawn-unit unit-hero-body 0 0 2 15", "set-var RessurectPlayer.Value 0 l_this l",
	"if-var v_ZombificationTime.Value == 0 normal",
	"if-var v_VeteranOfPain.Value == 4 elite",
	"if-var r_100 >= 33 normal",
	"label elite",
	"set-var RessurectPlayer.Value 0 v_RessurectPlayerPain.Value l",
	"set-var Ressurect.Value 0 5 l",
	"label normal",
    "exact-frame 76", "unbreakable end", "wait 1",}
local HeroDeathExtreme = {"unbreakable begin", 
	"exact-frame 77", "spawn-missile missile-extreme-gibs 20 20 0 0 pixel", "wait 3",
	"exact-frame 78", "wait 3",
	"exact-frame 79", "wait 3",
	"exact-frame 80", "wait 3",
	"exact-frame 81", "wait 3",
	"exact-frame 82", "wait 3",
	"exact-frame 83", "wait 3",
	"exact-frame 84", "wait 3",
	"exact-frame 85", "wait 2000",
    "exact-frame 85", "unbreakable end", "wait 1",}

DefineAnimations("animations-hero-body", {
  Still = {"label begin","exact-frame 76","if-var v_Arg1.Value > 0 still", "exact-frame 76","wait 1", "goto end", 
  "label ressurect", 
  "spawn-unit unit-zombie-bfg-body 0 0 2 v_RessurectPlayer.Value jointoai", "set-var RessurectPlayer.Value 0 v_RessurectPlayer.Value l", "set-var Ressurect.Value 0 2 l", "goto end",
  "label defibrillation",
  "spawn-unit unit-hero 0 0 2 v_RessurectPlayer.Value",
  "set-var HitPoints.Percent 0 30 l",
  "set-var ShieldPoints.Value == 0 l",
  "goto end",
  "label diedemon", "die demon_eating","wait 2",
  "label still","exact-frame 76", "wait 1", 
  "if-var v_UnitFlags.Value & "..unitFlags.UF_KillFromDemon.." diedemon",
  "if-var v_Ressurect.Value >= 2 ressurect", 
  "if-var v_DoneDefibrillation.Value == 1 defibrillation",
  "set-var Arg1.Value 2 1","goto begin","label end","wait 1","die ressurect","wait 2"},
  Death_demon_eating = {"unbreakable begin","exact-frame 76","spawn-missile missile-gibs 20 20 0 0 pixel","wait 3","unbreakable end","wait 1",},
  Death = {"unbreakable begin","exact-frame 76","unbreakable end","wait 1",}
})

DefineAnimations("animations-hero", {
  Still = HeroStill,
  Move = HeroMove,
  Attack = {"unbreakable begin",
  "if-var t__Distance.Value != 1 normal",
  "if-var S_spell-hero-melee == 0 normal",
  "if-var g_Building == 1 normal",
  "if-var g_AirUnit == 1 normal",
  "if-var g_organic != 1 normal",
  "goto melee",
  "label normal",
	 "set-var ShieldPiercing.Value = 0",
  "if-var v_Weapon.Value == 1 rocket",
  "if-var v_Weapon.Value == 2 unmaker",
	  "set-var DamageType 0 shell",
	  "set-var LightArmorDamage.Value 0 v_LightArmorDamage2.Value",
	  "set-var CombatArmorDamage.Value 0 v_CombatArmorDamage2.Value",
	  "set-var HeavyArmorDamage.Value 0 v_HeavyArmorDamage2.Value",
	  "set-var FleshArmorDamage.Value 0 v_FleshArmorDamage2.Value",
	  "set-var HeavyFleshArmorDamage.Value 0 v_HeavyFleshArmorDamage2.Value",
	  "set-var AirFleshArmorDamage.Value 0 v_AirFleshArmorDamage2.Value",
	  "set-var MechanicalArmorDamage.Value 0 v_MechanicalArmorDamage2.Value",
	  "set-var AirMechanicalArmorDamage.Value 0 v_AirMechanicalArmorDamage2.Value",
	  "set-var BuildingArmorDamage.Value 0 v_BuildingArmorDamage2.Value",
	  "set-var HeavyBuildingArmorDamage.Value 0 v_HeavyBuildingArmorDamage2.Value",
	  "set-var CursedArmorDamage.Value 0 v_CursedArmorDamage2.Value",
	  "frame 60", "wait 3", 
	  "frame 65", "attack", "sound ssg fire", "wait 5", 
	  "frame 60", "wait 6", 
	  "sound ssg open", "wait 6",
	  "sound ssg load", "wait 4", 
	  "sound ssg load", "wait 4",
	  "sound ssg load", "wait 4",
	  "sound ssg load", "wait 4",
	  "sound ssg close", "wait 4", "goto end",
	"label rocket",
	  "set-var DamageType 0 extreme",
	  "set-var LightArmorDamage.Value 0 v_LightArmorDamage3.Value",
	  "set-var CombatArmorDamage.Value 0 v_CombatArmorDamage3.Value",
	  "set-var HeavyArmorDamage.Value 0 v_HeavyArmorDamage3.Value",
	  "set-var FleshArmorDamage.Value 0 v_FleshArmorDamage3.Value",
	  "set-var HeavyFleshArmorDamage.Value 0 v_HeavyFleshArmorDamage3.Value",
	  "set-var AirFleshArmorDamage.Value 0 v_AirFleshArmorDamage3.Value",
	  "set-var MechanicalArmorDamage.Value 0 v_MechanicalArmorDamage3.Value",
	  "set-var AirMechanicalArmorDamage.Value 0 v_AirMechanicalArmorDamage3.Value",
	  "set-var BuildingArmorDamage.Value 0 v_BuildingArmorDamage3.Value",
	  "set-var HeavyBuildingArmorDamage.Value 0 v_HeavyBuildingArmorDamage3.Value",
	  "set-var CursedArmorDamage.Value 0 v_CursedArmorDamage3.Value",
		"frame 40", "wait 3", 
		"frame 45", "spawn-missile missile-rocket 0 0 0 0 damage.totarget", "sound cyber launch", "wait 5", 
		"frame 40", "wait 30", "goto end",
	"label melee",
   "set-var DamageType 0 melee",
   "set-var ShieldPiercing.Value = 1",
	  "set-var LightArmorDamage.Value 0 25",
	  "set-var CombatArmorDamage.Value 0 25",
	  "set-var HeavyArmorDamage.Value 0 20",
	  "set-var FleshArmorDamage.Value 0 25",
	  "set-var HeavyFleshArmorDamage.Value 0 20",
	  "set-var AirFleshArmorDamage.Value 0 0",
	  "set-var MechanicalArmorDamage.Value 0 0",
	  "set-var AirMechanicalArmorDamage.Value 0 0",
	  "set-var BuildingArmorDamage.Value 0 0",
	  "set-var HeavyBuildingArmorDamage.Value 0 0",
	  "set-var CursedArmorDamage.Value 0 50",
	  "if-var v_DoomerFist.Value == 1 fist1",
	  "frame 120", 
	  "set-var DoomerFist.Value == 1", "goto fistcont",
	  "label fist1",
	  "frame 125", 
	  "set-var DoomerFist.Value == 0",
	  "label fistcont",
	  "spawn-missile missile-claw-bite 0 0 0 0 damage.totarget", "sound revenant-punch", "wait 7",
  "goto end",
	"label unmaker",
	  "set-var DamageType 0 basic",
	  "set-var ShieldPiercing.Value = 1",
	  "set-var LightArmorDamage.Value 0 5",
	  "set-var CombatArmorDamage.Value 0 5",
	  "set-var HeavyArmorDamage.Value 0 5",
	  "set-var FleshArmorDamage.Value 0 8",
	  "set-var HeavyFleshArmorDamage.Value 0 8",
	  "set-var AirFleshArmorDamage.Value 0 5",
	  "set-var MechanicalArmorDamage.Value 0 0",
	  "set-var AirMechanicalArmorDamage.Value 0 0",
	  "set-var BuildingArmorDamage.Value 0 0",
	  "set-var HeavyBuildingArmorDamage.Value 0 0",
	  "set-var CursedArmorDamage.Value 0 12",
		"frame 110", "wait 1", 
		"frame 115", "spawn-missile missile-unmaker 0 0 0 0 damage.totarget", "sound unmaker attack", "wait 1", 
	"label end",
	"unbreakable end", "wait 1"
	},
  SpellCast = {"unbreakable begin", 
  "if-var s_spell-hero-melee == 1 melee",
  "if-var s_spell-hero-select-rl-for-ai == 1 quick",
  "if-var s_spell-hero-select-quad-for-ai == 1 quick",
  "if-var s_spell-hero-select-rl == 1 quick",
  "if-var s_spell-hero-select-quad == 1 quick",
  "if-var s_spell-hero-select-unmaker == 1 quick",
  "if-var s_spell-hero-soulsphere == 1 power",
  "if-var s_spell-hero-invisibility == 1 powerinvis",
  "if-var s_spell-hero-doomsphere == 1 powerdoom",
  "if-var s_spell-hero-invulnerability == 1 powerinvuln",
  "frame 50", 
  "set-var DamageType 0 extreme",
  "set-var ShieldPiercing.Value = 0",
  "set-var LightArmorDamage.Value 0 v_LightArmorDamage4.Value",
	  "set-var CombatArmorDamage.Value 0 v_CombatArmorDamage4.Value",
	  "set-var HeavyArmorDamage.Value 0 v_HeavyArmorDamage4.Value",
	  "set-var FleshArmorDamage.Value 0 v_FleshArmorDamage4.Value",
	  "set-var HeavyFleshArmorDamage.Value 0 v_HeavyFleshArmorDamage4.Value",
	  "set-var AirFleshArmorDamage.Value 0 v_AirFleshArmorDamage4.Value",
	  "set-var MechanicalArmorDamage.Value 0 v_MechanicalArmorDamage4.Value",
	  "set-var AirMechanicalArmorDamage.Value 0 v_AirMechanicalArmorDamage4.Value",
	  "set-var BuildingArmorDamage.Value 0 v_BuildingArmorDamage4.Value",
	  "set-var HeavyBuildingArmorDamage.Value 0 v_HeavyBuildingArmorDamage4.Value",
	  "set-var CursedArmorDamage.Value 0 v_CursedArmorDamage4.Value",
  "sound bfg charge", "wait 34",
  "frame 55", "rotate target", "attack", "sound bfg shot", "wait 3", 
  "frame 50", "wait 5", "sound bfg reload", "wait 80", "goto end",
  "label melee",
   "set-var DamageType 0 extreme",
	  "set-var LightArmorDamage.Value 0 20",
	  "set-var CombatArmorDamage.Value 0 20",
	  "set-var HeavyArmorDamage.Value 0 15",
	  "set-var FleshArmorDamage.Value 0 20",
	  "set-var HeavyFleshArmorDamage.Value 0 17",
	  "set-var AirFleshArmorDamage.Value 0 0",
	  "set-var MechanicalArmorDamage.Value 0 0",
	  "set-var AirMechanicalArmorDamage.Value 0 0",
	  "set-var BuildingArmorDamage.Value 0 0",
	  "set-var HeavyBuildingArmorDamage.Value 0 0",
	  "set-var CursedArmorDamage.Value 0 40",
	  "if-var v_DoomerFist.Value == 1 fist1",
	  "frame 120", 
	  "set-var DoomerFist.Value == 1", "goto fistcont",
	  "label fist1",
	  "frame 125", 
	  "set-var DoomerFist.Value == 0",
	  "label fistcont",
	  "set-var ShieldPiercing.Value 0 1",
	  "attack", "sound revenant-punch", "wait 7",
  "goto end",
  "label powerinvis",
  "attack", "sound invilerability", 
  "set-var Invisible.Max = v_DoomerInvisGive.Value",
  "set-var Invisible.Value = v_DoomerInvisGive.Value",
  "set-var Invisible.Enable = 1",
  "goto end",
  "label powerdoom",
  "set-var Bloodlust.Max = v_DoomerDoomGive.Value",
  "set-var Bloodlust.Value = v_DoomerDoomGive.Value",
  "set-var Bloodlust.Enable = 1",
  "goto power",
  "label powerinvuln",
  "set-var UnholyArmor.Max = v_DoomerInvulnGive.Value",
  "set-var UnholyArmor.Value = v_DoomerInvulnGive.Value",
  "set-var UnholyArmor.Enable = 1",
  "label power", "attack", "sound invilerability", "goto end",
  "label quick", "attack",
  "label end",
  "unbreakable end", "wait 1",},
  Death = HeroDeath,
  Death_extreme = HeroDeathExtreme,
  Death_fire = {"unbreakable begin","frame 130","spawn-unit unit-burning 0 0 5 15","wait 100","unbreakable end","wait 1",},
})

UnitName = "unit-hero"
BaseDamage = UnitInfo(UnitName, const.Unit_BaseDmg)
DamageType = UnitInfo(UnitName, const.Unit_DamageType)
BaseDamage2 = UnitInfo(UnitName, const.Unit_BaseDmg2)
DamageType2 = UnitInfo(UnitName, const.Unit_DamageType2)
BaseDamage3 = 350
DamageType3 = "anti-flesh"
DefineUnitType(UnitName, { Name = _("Doomer"),
  -- Drawing
  Image = {"file", "graphics/uac/units/herodestroyer.png", "size", {43, 43}},
  Shadow = {"file", "graphics/uac/units/herodestroyer-s.png", "size",{43, 43},"offset", {0, 0}},
  Animations = "animations-hero", Icon = "icon-hero",
  TileSize = {1, 1}, BoxSize = {30, 45},
  DrawLevel = UnitInfo(UnitName, const.Unit_Draw),
  Flip = false, NumDirections = 8,
  Type = "land",
  Impact = {"shell", "missile-red-shell-meat", "melee", "missile-red-melee-meat"},
  MissileOffsets = {{{6, -4}, {10, -4}, {17, -1}, {16, -1}, {-6, 0}, {-12, -1}, {-17, -1}, {-10, -3}}},
  -- Properties
  Costs = {"time", UnitInfo(UnitName, const.Unit_Build), "minerals", UnitInfo(UnitName, const.Unit_MinCost),"energy",UnitInfo(UnitName, const.Unit_EngCost)},
  HitPoints = UnitInfo(UnitName, const.Unit_HP),
  SightRange = UnitInfo(UnitName, const.Unit_Sight), ComputerReactionRange = UnitInfo(UnitName, const.Unit_Comp), 
  PersonReactionRange = UnitInfo(UnitName, const.Unit_Person),
  MaxAttackRange = UnitInfo(UnitName, const.Unit_AtkRange),
  Priority = 30,
  Points = UnitInfo(UnitName, const.Unit_Points),
  Demand = UnitInfo(UnitName, const.Unit_Supply),
  RegenerationRate = 1,
  Weapon = 0,
  Mana = UnitInfo(UnitName, const.Unit_Mana),
  PoisonDrain = 1,
  ShieldPoints = UnitInfo(UnitName, const.Unit_SP),
  CanCastSpell = {"spell-hero-melee", "spell-hero-bfg", "spell-hero-bfg-for-ai", "spell-hero-select-rl", 
  "spell-hero-select-quad", "spell-hero-select-unmaker", "spell-hero-select-rl-for-ai", 
  "spell-hero-select-quad-for-ai", "spell-hero-soulsphere", "spell-hero-invisibility", 
  "spell-hero-doomsphere",  "spell-hero-invulnerability"},
  AutoCastActive = {"spell-hero-melee"},
  DoomerInvisGive = 900,
  DoomerDoomGive = 300,
  DoomerInvulnGive = 300,
  -- Damage and armor part
  BasicDamage = 1, PiercingDamage = 1, Missile = "missile-shotgun-shot3",
  IsHeavyArmor = 1,
  BaseDamage = BaseDamage,
  BaseDamage2 = BaseDamage2,
  BaseDamage3 = BaseDamage3,

  LightArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_Light),
  CombatArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_Medium),
  HeavyArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_Heavy),
  
  FleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_Flesh),
  HeavyFleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_HeavyFlesh),
  AirFleshArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_AirFlesh),
  
  MechanicalArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_Mechanical),
  AirMechanicalArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_AirMechanical),
  
  BuildingArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_Building),
  HeavyBuildingArmorDamage2 = GetArmorDamage(BaseDamage, DamageType, const.UnitArmor_HeavyBuilding),
  
  CursedArmorDamage2 = GetCursedDamage(BaseDamage),
  
  LightArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_Light),
  CombatArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_Medium),
  HeavyArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_Heavy),
  
  FleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_Flesh),
  HeavyFleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_HeavyFlesh),
  AirFleshArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_AirFlesh),
  
  MechanicalArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_Mechanical),
  AirMechanicalArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_AirMechanical),
  
  BuildingArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_Building),
  HeavyBuildingArmorDamage3 = GetArmorDamage(BaseDamage2, DamageType2, const.UnitArmor_HeavyBuilding),
  
  CursedArmorDamage3 = GetCursedDamage(BaseDamage2),
  
  LightArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 1),
  CombatArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 2),
  HeavyArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 3),
  
  FleshArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 4),
  HeavyFleshArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 5),
  AirFleshArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 6),
  
  MechanicalArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 7),
  AirMechanicalArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 8),
  
  BuildingArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 9),
  HeavyBuildingArmorDamage4 = GetArmorDamage(BaseDamage3, DamageType3, 10),
  
  CursedArmorDamage4 = GetCursedDamage(BaseDamage3),
  ----------------------
  -- Flags
  ShieldPiercing = 1,
  UAC = true,  
  -- CanGroundAttack = true,
  GroundAttack = true,
  CanTargetLand = true,
  CanTargetAir = true,
  LandUnit = true,
  BigUnit = true,
  Hero = true,
  CanAttack = true,
  ShowArmor = true,
  organic = true,
  SelectableByRectangle = true,
  -- Others
  RightMouseAction = "attack",
  OnEachSecond = UpdateVeteranStatus,
  Sounds = {
    "selected", "hero-selected",
    "acknowledge", "hero-acknowledge",
	"attack", "hero-attack",
    "ready", "hero-ready",
    "help", "uac unit under attack",
	"dead", "extreme","vgavnonah",
	"dead", "fire","marine fire death",
    "dead", "uac marine death"} } )

DefineUnitType("unit-hero-body", { Name = _("Doomer Body"),
  Image = {"file", "graphics/uac/units/herodestroyer.png", "size", {43, 43}},
  Animations = "animations-hero-body", Icon = "icon-cancel",
  HitPoints = 150,
  DrawLevel = 10,
  IsHeavyFleshArmor = 1,
  Indestructible = 1,
  NumDirections = 8, Flip = false,
  NoRandomPlacing = true,
  TileSize = {1, 1}, BoxSize = {31, 31},
  SightRange = 0,
  Arg1 = 3600,
  OnEachCycle = HandleDefibrillation,
  BasicDamage = 0, PiercingDamage = 0, Missile = "missile-none",
  Priority = 0,
  Type = "land",
  NonSolid = true,
  UAC = true,
  Dead = true,
  IsNotSelectable = true,
  Sounds = {} })
